services:
    users_db:
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_PASSWORD: chatAppPass
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
        volumes:
            - pgdata_users:/var/lib/postgresql/data

    users_server:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile_usersServer
        ports:
            - "50051:50051"
        environment:
            DB_HOST: users_db
            DB_PORT: 5432
            DB_USER: postgres
            DB_PASSWORD: chatAppPass
            DB_NAME: postgres
        depends_on:
            - users_db

    zookeeper:
        restart: always
        image: confluentinc/cp-zookeeper:latest
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        ports:
            - 2181:2181

    kafka:
        restart: always
        image: confluentinc/cp-kafka:latest
        ports:
            - 9092:9092
            - 29092:29092
        depends_on:
            - zookeeper
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    chat_db:
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_PASSWORD: chatAppPass
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
        volumes:
            - pgdata_chat:/var/lib/postgresql/data

    chat_server:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile_chatServer
        environment:
            DB_HOST: chat_db
            DB_PORT: 5432
            DB_USER: postgres
            DB_PASSWORD: chatAppPass
            DB_NAME: postgres
            KAFKA_BROKER: kafka:9092
        depends_on:
            - kafka
            - chat_db

volumes:
    pgdata_users:
    pgdata_chat:
