FROM golang:1.22 AS builder

WORKDIR /app

COPY . .

RUN go mod tidy
RUN CGO_ENABLED=0 GOOS=linux go build -o main chatServer/main.go

FROM alpine:latest

RUN apk add --no-cache ca-certificates postgresql-client netcat-openbsd

COPY --from=builder /app/wait-for-kafka-and-db.sh /wait-for-kafka-and-db.sh
COPY --from=builder /app/main /main

RUN chmod +x /wait-for-kafka-and-db.sh

CMD ["/wait-for-kafka-and-db.sh", "chat_db", "5432", "kafka", "9092", "./main"]
